### PR TITLE
Translation of chapter 0x01 to Persian (#399)

### PR DESCRIPTION
**Pull request by Snbig**
* Update 0x01-Foreword.md

Co-authored-by: Dorna Azhirak <@nameddorna>
Co-authored-by: Mahsa Omidvar <@MahsaOmidvar>
Co-authored-by: Hossein Sa <@hosseinsss>
Co-authored-by: Alireza Mazhari <@alireza-mzhi>
Co-authored-by: Mahmood Mohammadian <@lampard200539>

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [ ] Your PR is linked to an issue.
- [ ] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [ ] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #399 .

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

### CODE REVIEW

**Comment by sushi2k** [comment]
Thanks for this PR. May I know if you already did some peer review of the content that you all created?

**Comment by hosseinsss** [comment]
Yes, i did.

**Comment by Snbig** [comment]
> Thanks for this PR. May I know if you already did some peer review of the content that you all created?

You're welcome.
Our methodology is based on real-time peer reviewing by the way that about 6 contributors start online translating of specific chapter reguarding to the linguistic rules and each one has perspective of others real-time translation results. After all translating process finished, two main collaborators review and integrate the results based on words qualities, rules and fluency . Also we use high order glossary to keep integrity of each translation PR.

**Comment by commjoen** [comment]
In order to speed up detection of issues with document generation, could you be so kind to create the next PR against OWASP:persian_automation of the MASVS? That way we can see the results of your hard work directly in a document build <3 !

**Pull request merged**
