### PR TITLE
Persian translation

### PR DESCRIPTION
**Pull request by RaminAT**
Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [ ] Your PR is linked to an issue.
- [ ] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [ ] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [ ] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #< insert number here >.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

### CODE REVIEW

**Comment by commjoen** [comment]
Thank you for your pr. Can you please target the Persian automation branch?

**Comment by commjoen** [comment]
If you create the MR towards OWASP:persian_automation we should be fine 👍

**Comment by RaminAT** [comment]
OK I did.

**Comment by commjoen** [comment]
@RaminAT , sorry for alll the confusion, is it ok if we continue wth this mr instead? As we will merge persian_automation to master now :D ... Still: can you please fix the markdown issues please :) ?

**Comment by commjoen** [comment]
Hi @RaminAT ! Thank you for providing your PR! Great job!
There seems to be a few challenges with the PR:

https://github.com/OWASP/owasp-masvs/pull/424/checks?check_run_id=565056802 shows markdown issues, can you fix those please?
There seems to be a conflict at Document-fa/0x02-Frontispiece.md

**Comment by RaminAT** [comment]
Hi is it OK now? I'm translating the rest today should I make PR to master next? thanks.

**Comment by commjoen** [comment]
It seems to be ok now , though the markdown-lint-check does not seem to come trough.

**Comment by commjoen** [comment]
The lint check seems to be broken, let me close and reopen it again.

**Comment by commjoen** [comment]
https://github.com/OWASP/owasp-masvs/pull/424/checks?check_run_id=578930567 shows quiet some Markdown lint issues. Can you please check/fix those :) ?

**Comment by RaminAT** [comment]
Markdown lint is green now.

**Pull request merged**
