### PR TITLE
Pdf spacings

### PR DESCRIPTION
**Pull request by commjoen**
This is a spacing PR to set the order of things in a better way. Please use gendocslocal.sh to generate the pdfs locally and review/update them

### CODE REVIEW

**Comment by OMTGreleaser** [comment]
Results for commit 2bffe08b83f0296948d1ddf2ac59061305b2ea06: Broken link result: 0 .
  
 Markdown result errorlength: 2 .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Comment by OMTGreleaser** [comment]
Results for commit 64e737abbf445bebac64de9b653a4ac9d94d7090: Broken link result: 0 .
  
 Markdown result errorlength: 3 .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Comment by OMTGreleaser** [comment]
Results for commit a722553510026da8230c027ba175d524c28ef223: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by OMTGreleaser** [comment]
Results for commit 82690271e4a38cacae042984ecd912a1bad13929: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by OMTGreleaser** [comment]
Results for commit 53db8b07642d47f4c2710b4968ebeb110edd6cad: Broken link result: 0 .
  
 Markdown result errorlength: 1 .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Comment by commjoen** [comment]
Indeed, time to move on!

**Pull request closed without merging**
