### PR TITLE
Added new items to V4

### PR DESCRIPTION
**Pull request by commjoen**
please review with care. I am very willing to adjust it. Most of these items just detail the existing controls.

### CODE REVIEW

**Comment by b-mueller** [comment]
Device binding is already handled in V8.13:

"Verify that the application implements a 'device binding' functionality when a mobile device is treated as being trusted. Verify that the device fingerprint is derived from multiple device properties."

Requirement added to chapter 4: This is similar to V4.5: "Verify that the remote service blocks login attempts in response to an excessive number of unsuccessful attempts." Agreed that this can be formulated better, as login attempts should not be blocked alltogether. Shall we replace V4.5 with your requirement?

**Comment by commjoen** [comment]
Agreed: do you want me to change this in this PR?

**Comment by b-mueller** [comment]
Ack!

**Comment by b-mueller** [comment]
I updated 4.5 to include the exponential back-off and user lock options. Also changed "login attempts" to "authentication credentials" to make it cover both of your suggestions.

| **4.5** | Verify that the remote service implements an exponential back-off, or temporarily locks the user account, when incorrect authentication credentials are submitted an excessive number of times . | ✓ | ✓ | ✓ | ✓ |

**Pull request closed without merging**
