### PR TITLE
Persian automation support

### PR DESCRIPTION
**Pull request by commjoen**
Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [x] Your PR is linked to an issue.
- [x] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [x] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [x] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #399.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
I used another pdf engine it works... (wkhtmltopdf)

```bash
root@44b9604be62d:/pandoc# cat /pandoc_makedocs.sh
#!/bin/bash

# NOTE: This script is not meant to be run locally on your machine (e.g. macOS). Docker will run it for you.

set -euo pipefail

FOLDER=$1
VERSION=$2

echo "FOLDER=${FOLDER}"
echo "VERSION=${VERSION}"

# Load the language metadata (env. vars)
. $FOLDER/LANGUAGE-METADATA

OUTPUT_BASE_NAME="OWASP_MASVS-${VERSION}"

# Put all chapters in order and CHANGELOG at the end
CHAPTERS="${FOLDER}/0x*.md ${FOLDER}/CHANGELOG.md"

# Use per-language tmp files for the cover and the first page
# Replace the placeholder {{MASVS-VERSION}} with the given VERSION and {{MASVS-LANGUAGE}} with the given LANGUAGETEXT
sed -e "s/{{MASVS-VERSION}}/$VERSION/g" -e "s/{{MASVS-LANGUAGE}}/$LANGUAGETEXT/g" ./tools/docker/cover.tex > tmp_cover-$LANGUAGE.tex
sed -e "s/{{MASVS-VERSION}}/$VERSION/g" ./tools/docker/first_page.tex > tmp_first_page-$LANGUAGE.tex

# latex-header.tex contains 2 placeholders for "using CJK fonts" and for the language itself: JP,SC,TC,KR (part of the font name)
# The following does the replacement and writes to a tmp file
if [ $LANGUAGE == "ja" ]; then
  sed -e "s/%%{{CJK}}//g" -e "s/{{CJK-LANG}}/JP/g" ./tools/docker/latex-header.tex > tmp_1_latex-header-$LANGUAGE.tex
  sed 's/^%%//' tmp_1_latex-header-$LANGUAGE.tex > tmp_latex-header-$LANGUAGE.tex
elif [ $LANGUAGE == "ko" ]; then
  sed -e "s/%%{{CJK}}//g" -e "s/{{CJK-LANG}}/KR/g" ./tools/docker/latex-header.tex > tmp_1_latex-header-$LANGUAGE.tex
  sed 's/^%%//' tmp_1_latex-header-$LANGUAGE.tex > tmp_latex-header-$LANGUAGE.tex
elif [ $LANGUAGE == "zhcn" ]; then
  sed -e "s/%%{{CJK}}//g" -e "s/{{CJK-LANG}}/SC/g" ./tools/docker/latex-header.tex > tmp_1_latex-header-$LANGUAGE.tex
  sed 's/^%%//' tmp_1_latex-header-$LANGUAGE.tex > tmp_latex-header-$LANGUAGE.tex
elif [ $LANGUAGE == "zhtw" ]; then
  sed -e "s/%%{{CJK}}//g" -e "s/{{CJK-LANG}}/TC/g" ./tools/docker/latex-header.tex > tmp_1_latex-header-$LANGUAGE.tex
  sed 's/^%%//' tmp_1_latex-header-$LANGUAGE.tex > tmp_latex-header-$LANGUAGE.tex
elif [ $LANGUAGE == "fa" ]; then
  sed 's/^%%%%//g' ./tools/docker/latex-header.tex > tmp_latex-header-$LANGUAGE.tex
else
  cp ./tools/docker/latex-header.tex tmp_latex-header-$LANGUAGE.tex
fi

# given that the formats below require markdown images instead of image tags: let's parse the files:
echo "processing image tags in $FOLDER/0x*.md"
for FILE in $FOLDER/0x*.md
do
  [ -f temp-$LANGUAGE ] && rm temp-$LANGUAGE
  sed -f tools/docker/imagereplace.sed $FILE > temp-$LANGUAGE
  cat temp-$LANGUAGE > $FILE
  [ -f temp-$LANGUAGE ] && rm temp-$LANGUAGE
done
# --columns 60 -> pandoc will attempt to wrap lines to the column width specified by --columns (default 72). We need it because of ZHCN.
# --toc to create a Table of Contents with the title from the loaded env. vars.
# -H to apply our customizations in the .tex header file
# --include-before-body -> to include the auto-generated cover and first page as the very beginning
pandoc --resource-path=.:${FOLDER} \
    --template=/.pandoc/templates/eisvogel.latex \
    --pdf-engine=wkhtmltopdf \
    --columns 60 \
    --toc -V toc-title:"${TOC_TITLE}" --toc-depth=1 \
    --metadata title="OWASP Mobile Application Security Verification Standard $VERSION" \
    -H tmp_latex-header-$LANGUAGE.tex -V linkcolor:blue \
    --include-before-body tmp_cover-$LANGUAGE.tex --include-before-body tmp_first_page-$LANGUAGE.tex \
    -o ${OUTPUT_BASE_NAME}-${LANGUAGE}.pdf $CHAPTERS

pandoc --resource-path=.:${FOLDER} \
    -f markdown \
    -t epub \
    --metadata title="OWASP Mobile Application Security Verification Standard" \
    --metadata lang="${LANGUAGE}" \
    --metadata author="Bernhard Mueller, Sven Schleier, Jeroen Willemsen, and Carlos Holguera" \
    --epub-cover-image=cover.jpg \
    -o ${OUTPUT_BASE_NAME}-${LANGUAGE}.epub $CHAPTERS

pandoc --resource-path=.:${FOLDER} \
    -f markdown \
    -t docx \
    --toc -N --columns 10000 --self-contained -s \
    --reference-doc tools/custom-reference.docx \
    -o ${OUTPUT_BASE_NAME}-${LANGUAGE}_WIP_.docx $CHAPTERS

kindlegen ${OUTPUT_BASE_NAME}-${LANGUAGE}.epub

rm tmp_first_page-$LANGUAGE.tex
rm tmp_cover-$LANGUAGE.tex
rm tmp_latex-header-$LANGUAGE.tex


if [[ "$LANGUAGE" = "ja" || "$LANGUAGE" = "ko" ||  "$LANGUAGE" = "zhcn" ||  "$LANGUAGE" = "zhtw" ]]; then
  rm tmp_1_latex-header-$LANGUAGE.tex
fi
root@44b9604be62d:/pandoc# wkhtmltopdf -V
wkhtmltopdf 0.12.5 (with patched qt)
root@44b9604be62d:/pandoc# /pandoc_makedocs.sh Document-fa SNAPSHOT
FOLDER=Document-fa
VERSION=SNAPSHOT
processing image tags in Document-fa/0x*.md
Loading pages (1/6)
Warning: Failed to load file:///pandoc/images/OWASP_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/CC-license.png (ignore)
Warning: Failed to load file:///pandoc/images/NowSecure_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/Randorisec_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/masvs-levels-new.jpg (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

*************************************************************
 Amazon kindlegen(Linux) V2.9 build 1028-0897292
 A command line e-book compiler
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

Info(prcgen):I1047: Added metadata dc:Title        "OWASP Mobile Application Security Verification Standard"
Info(prcgen):I1047: Added metadata dc:Date         "2020-03-21T23:13:30Z"
Info(prcgen):I1047: Added metadata dc:Creator      "Bernhard Mueller, Sven Schleier, Jeroen Willemsen, and Carlos Holguera"
Info(prcgen):I1052: Kindle support cover images but does not support cover HTML. Hence using the cover image specified and suppressing cover HTML in content.     URL: /tmp/mobi-skFPxr/EPUB/text/cover.xhtml
Info(prcgen):I1002: Parsing files  0000016
Info(prcgen):I1015: Building PRC file
Info(prcgen):I1006: Resolving hyperlinks
Info(pagemap):I8000: No Page map found in the book
Info(prcgen):I1045: Computing UNICODE ranges used in the book
Info(prcgen):I1046: Found UNICODE range: Basic Latin [20..7E]
Info(prcgen):I1046: Found UNICODE range: General Punctuation - Windows 1252 [2018..201A]
Info(prcgen):I1046: Found UNICODE range: Latin-1 Supplement [A0..FF]
Info(prcgen):I1046: Found UNICODE range: Basic Arabic [600..6FF]
Info(prcgen):I1046: Found UNICODE range: Dingbats [2700..27BF]
Info(prcgen):I1017: Building PRC file, record count:   0000024
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  47.28%
Info(prcgen):I1040: The document identifier is: "OWASP_Mobile-ation_Standard"
Info(prcgen):I1041: The file format version is V6
Info(prcgen):I1031: Saving PRC file
Info(prcgen):I1032: PRC built successfully
Info(prcgen):I1016: Building enhanced PRC file
Info(prcgen):I1007: Resolving mediaidlinks
Info(prcgen):I1011: Writing mediaidlinks
Info(prcgen):I1009: Resolving guide items
Info(prcgen):I1017: Building PRC file, record count:   0000030
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  47.89%
Info(prcgen):I1041: The file format version is V8
Info(prcgen):I15000:  Approximate Standard Mobi Deliverable file size :   0000329KB
Info(prcgen):I15001:  Approximate KF8 Deliverable file size :   0000343KB
Info(prcgen):I1036: Mobi file built successfully
root@44b9604be62d:/pandoc#
```

but notice if you use `apt install -y wkhtmltopdf` it will have an error, because Debian repo seems it's not updated.
```bash
root@4f7829c9d0ff:/pandoc# wkhtmltopdf -V
wkhtmltopdf 0.12.3.2
root@4f7829c9d0ff:/pandoc# /pandoc_makedocs.sh Document-fa SNAPSHOT
FOLDER=Document-fa
VERSION=SNAPSHOT
processing image tags in Document-fa/0x*.md
QXcbConnection: Could not connect to display
Error producing PDF.
```

so update it (and ignore dependency errors)

```bash
root@31ec71305949:/pandoc# wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb && (dpkg -i wkhtmltox_0.12.5-1.stretch_amd64.deb || apt install -f -y && dpkg -i wkhtmltox_0.12.5-1.stretch_amd64.deb)
....
root@31ec71305949:/pandoc# wkhtmltopdf -V
wkhtmltopdf 0.12.5 (with patched qt)
root@31ec71305949:/pandoc# /pandoc_makedocs.sh Document-fa SNAPSHOT
FOLDER=Document-fa
VERSION=SNAPSHOT
processing image tags in Document-fa/0x*.md
Loading pages (1/6)
Warning: Failed to load file:///pandoc/images/OWASP_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/CC-license.png (ignore)
Warning: Failed to load file:///pandoc/images/NowSecure_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/Randorisec_logo.png (ignore)
Warning: Failed to load file:///pandoc/images/masvs-levels-new.jpg (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

*************************************************************
 Amazon kindlegen(Linux) V2.9 build 1028-0897292
 A command line e-book compiler
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

Info(prcgen):I1047: Added metadata dc:Title        "OWASP Mobile Application Security Verification Standard"
Info(prcgen):I1047: Added metadata dc:Date         "2020-03-21T23:32:21Z"
Info(prcgen):I1047: Added metadata dc:Creator      "Bernhard Mueller, Sven Schleier, Jeroen Willemsen, and Carlos Holguera"
Info(prcgen):I1052: Kindle support cover images but does not support cover HTML. Hence using the cover image specified and suppressing cover HTML in content.     URL: /tmp/mobi-XHy1Qu/EPUB/text/cover.xhtml
Info(prcgen):I1002: Parsing files  0000016
Info(prcgen):I1015: Building PRC file
Info(prcgen):I1006: Resolving hyperlinks
Info(pagemap):I8000: No Page map found in the book
Info(prcgen):I1045: Computing UNICODE ranges used in the book
Info(prcgen):I1046: Found UNICODE range: Basic Latin [20..7E]
Info(prcgen):I1046: Found UNICODE range: General Punctuation - Windows 1252 [2018..201A]
Info(prcgen):I1046: Found UNICODE range: Latin-1 Supplement [A0..FF]
Info(prcgen):I1046: Found UNICODE range: Basic Arabic [600..6FF]
Info(prcgen):I1046: Found UNICODE range: Dingbats [2700..27BF]
Info(prcgen):I1017: Building PRC file, record count:   0000024
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  47.28%
Info(prcgen):I1040: The document identifier is: "OWASP_Mobile-ation_Standard"
Info(prcgen):I1041: The file format version is V6
Info(prcgen):I1031: Saving PRC file
Info(prcgen):I1032: PRC built successfully
Info(prcgen):I1016: Building enhanced PRC file
Info(prcgen):I1007: Resolving mediaidlinks
Info(prcgen):I1011: Writing mediaidlinks
Info(prcgen):I1009: Resolving guide items
Info(prcgen):I1017: Building PRC file, record count:   0000030
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  47.89%
Info(prcgen):I1041: The file format version is V8
Info(prcgen):I15000:  Approximate Standard Mobi Deliverable file size :   0000329KB
Info(prcgen):I15001:  Approximate KF8 Deliverable file size :   0000343KB
Info(prcgen):I1036: Mobi file built successfully
```

**Comment by Ali-Razmjoo** [comment]
sorry for this delay in answer, I'm overloaded these days, but anyway I've looked into your new code, I know these solutions are not standard or hacky, but hey that's what we do here :D, I could generate a Persian PDF but converting `OWASP_MASVS-SNAPSHOT-fa_WIP_.docx` using `apt install unoconv -y && doc2pdf OWASP_MASVS-SNAPSHOT-fa_WIP_.docx` the output is `OWASP_MASVS-SNAPSHOT-fa_WIP_.pdf` and looks fine to me!

do you want to fix the problem, or remove it and use the new solution? maybe use this temporary fix, for now, to be on time if you defined a deadline, and you can fix it later. actually no one will look into your codebuild steps so you can just let it be there? :D 

your thoughts?

**Comment by Snbig** [comment]
> sorry for this delay in answer, I'm overloaded these days, but anyway I've looked into your new code, I know these solutions are not standard or hacky, but hey that's what we do here :D, I could generate a Persian PDF but converting `OWASP_MASVS-SNAPSHOT-fa_WIP_.docx` using `apt install unoconv -y && doc2pdf OWASP_MASVS-SNAPSHOT-fa_WIP_.docx` the output is `OWASP_MASVS-SNAPSHOT-fa_WIP_.pdf` and looks fine to me!
> 
> do you want to fix the problem, or remove it and use the new solution? maybe use this temporary fix, for now, to be on time if you defined a deadline, and you can fix it later. actually no one will look into your codebuild steps so you can just let it be there? :D
> 
> your thoughts?

Thank you for you solution but doc2pdf requires Microsoft office libraries so we may run into problem at the rest. I suggested @commjoen to use Libreoffice with just `libreoffice --headless --convert-to pdf OWASP_MASVS-SNAPSHOT-fa_WIP_.docx` command and results are fine but he said :
> nope, i rather have something that is the same for all as much as possible. because that will simplify maintenance and updating document features

Other solution?  😫

**Comment by commjoen** [comment]
For now we have a stopgap solution, as suggested by @Snbig : have a container convert the docx to PDF (https://github.com/OWASP/owasp-masvs/suites/559335814/artifacts/3616897 as a first result). Now you can at least have some sort of PDF ^^. Ofcourse, we will look for having the right tex distribution in a container so we can have much faster generation of your PDFS eventually. But at least there is basic PDF support now ^^.

**Comment by Ali-Razmjoo** [comment]
not sure if you are aware, ToC is not loading in the Persian PDF.

**Comment by commjoen** [comment]
> not sure if you are aware, ToC is not loading in the Persian PDF. also I've posted this issue in our Persian community, let's see if anyone has a solution for this.

That is a consequence from the doc to pdf solution I am afraid. It should be fixed when we have a a pandoc with latex2019 base container...

**Comment by Ali-Razmjoo** [comment]
but the version I sent you in slack is fine, did you change the method in generating from doc file?

**Comment by commjoen** [comment]
I used an open office container. Will test the converter again on our current container

**Comment by commjoen** [comment]
@Ali-Razmjoo & @Snbig , as you can see I was able to dockerize the hack to generate a better PDF. now all i need is a way to prepend the cover ^^ and then we are done in a hackish way...

**Comment by commjoen** [comment]
@Ali-Razmjoo & @Snbig : does the Persian content need more reviewing at this pr? or is it already reviewed so we can merge it to master?

**Comment by commjoen** [comment]
Content is reviewed, so we can move this into master indeed

**Pull request merged**
