### PR TITLE
Update 0x11-V6_Interaction_with_the_environment.md

### PR DESCRIPTION
**Pull request by TmmmmmR**

### CODE REVIEW

**Comment by b-mueller** [comment]
Hi Abdessamad, what is the risk of loading WebView content from a local resource?

**Comment by TmmmmmR** [comment]
Hello Mueller,

The risk could be "client side injection" by local user generated/downloaded content (for example an e-mail application that display downloaded attached files).

As a best practice, apps that need to display untrusted content inside a WebView should display that content within a DOM that prevents client side attacks (example : access to sensitive data). This could be done by hosting the content on a dedicated/trusted domain to host user generated/downloaded content.

**Comment by b-mueller** [comment]
I see what you mean. So for example, if an attachment would be downloaded to a local folder, and then opened in a WebView with a file:// URL? Good point.

**Comment by b-mueller** [comment]
@TmmmmmR I'm merging this but might change the wording a bit. Can you contribute a test case for this to the testing guide? We need to clarify the risk for Android and iOS. Can also discuss it on the Slack channel later.

**Comment by b-mueller** [comment]
Made it a L1 requirement and moved to 6.8.

**Pull request merged**
