### PR TITLE
135/automation

### PR DESCRIPTION
**Pull request by commjoen**
This PR covers the following issues
#135  - Update automatic releasing for masvs (which includes updates for french, spanish, english, japanese, german, chinese)
#144  - Do the french translation
#140 - Fix 1.1 release english pdf and re-release (4.7 and 4.8 got mixed)
#156 - Do the Chinese translation

For every reviewer: Please check your translation to see whether you are ok with the changes/fixes applied there...

### CODE REVIEW

**Comment by commjoen** [comment]
Hi @coky-t, thank you for your feedback! I hope I fixed it correctly :).

**Comment by commjoen** [comment]
Hi @codethatrocks, I think I fixed all the feedback. Can you approve the PR please?

**Comment by commjoen** [comment]
@martinmarsicano it should be everywhere, i will add it today :)

**Comment by ninedter** [comment]
Chinese version ok

**Comment by codethatrocks** [comment]
rest of german version looks good (except for the mentioned minor change proposals) :)

**Comment by romualdszkudlarek** [comment]
My comments concerning the French version:
- as the changelog is not translated yet, it should not appear in the first place. I suggest having it at the end of the document for the moment (or have it translated inspite of my vote on Slack)
- the drawing on page 8 is not translated into French even if the French version exists in the code repo (https://github.com/OWASP/owasp-masvs/blob/master/Document-fr/images/masvs-levels-new_fr.jpg). I guess the name of the translated file is not the right one in the repo, or the name of the file is not the right one in the script for generation.

**Comment by commjoen** [comment]
Will update the french version to have the new french picutre in. Next, i will put the changelog after the foreword in order to show the actual language being used first ;-).

**Comment by commjoen** [comment]
@romualdszkudlarek : I have updated the documents, it should be ok now (changelog is after foreword)

**Comment by commjoen** [comment]
I can change changelog's title to "International changelog" for now... if that would help...

**Pull request merged**
