### PR TITLE
#224: Adding japanese changelog translation

### PR DESCRIPTION
**Pull request by commjoen**
Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [x] Your PR is linked to an issue.
- [x] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [x] All links are valid and use HTTPS and have been formatted as [TEXT](URL “NAME”)
- [x] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #224.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

### CODE REVIEW

**Comment by OMTGreleaser** [comment]
Results for commit 9100ff739556594afcaca421f9246906d00a0bde: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by commjoen** [comment]
Hi there, a minor complexity; as we are preparing our next release (final for Q3), can you please add this part translated to the changelog as well :( ?

```## V1.1.4 4 July 2019 - Summit edition (WIP)

The following changes are part of release 1.1.4:

- Fix all markdown issues.
- Updates in the French and Spanish translations.
- Translated the changelog in Chinese (ZHTW) and Japanese.
- Automated verification of the the markdown and links.
- Added identification codes to the requirements, which will be included in the future version of the MSTG in order to find the recommendations and testcases easily.
- Reduced the repo size and added Generated to the .gitignore.
- Added a Code of Conduct & Contributing guidelines.
- Added a Pull-Request template.
- Updated the sync with the repo in use for hosting the Gitbook website.
- Updated the scripts to generate XML/JSON/CSV for all the translations.
```

**Comment by coky-t** [comment]
I checked them.
There is no problem with japanese translation up to V1.1.3, but there is a minor problem.
The date has been lost at V1.1.2 and V1.1.3 in CHANGELOG file of Document-ja. 
And the same applies to CHANGELOG files of Document-es/fr/zhtw.

**Comment by commjoen** [comment]
Thanks @coky-t ! Can you please add the date  and the V1.1.4 notes to the japanese file? I will do the same to the ZHTW, and FR.

**Comment by OMTGreleaser** [comment]
Results for commit ab9bde12d60b2ca11ebd8261db31a4e1fc8233aa: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by OMTGreleaser** [comment]
Results for commit 1ee6c3c6cdcb96f00e7be1d72fe575600501ffb9: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by OMTGreleaser** [comment]
Results for commit e4d24c83062be236b86a8f1f7dc483a4d0ea948f: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Comment by OMTGreleaser** [comment]
Results for commit 78d1431a0b7313252521dc58c2af57d9d9008328: Broken link result: 0 .
  
 Markdown result errorlength: 0 .

**Pull request merged**
