### PR TITLE
fix ".should ultimately be a risk-based decision."

### PR DESCRIPTION
**Pull request by WuglyakBolgoink**
fix substring `"or not should ultimately be a risk-based decision, which is taken/communicated with the business owners."`

original:
```
I: Although we recommend implementing MASVS-L1 controls in every app, implementing a control or not should ultimately be a risk-based decision, which is taken/communicated with the business owners.
```
simple google translate
```
I: Хотя мы рекомендуем внедрять элементы управления MASVS-L1 в каждое приложение, внедрение элемента управления или отказ от него в конечном итоге должно быть основанным на оценке риска решением, которое принимается / доводится до сведения владельцев бизнеса.
```

Thank you for submitting a Pull Request to the Mobile Application Security Verification Standard. Please make sure that:

- [x] Your PR is linked to an issue. -> https://github.com/OWASP/owasp-masvs/issues/492
- [x] Your PR follows the [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines")
- [x] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?

This PR covers issue #< insert number here >.

If your pull-request has a focus of rewriting a requirement and/or adding a new one, please make sure you have a backing issue in which your change has been discussed and agreed. If there is none, then your PR will be closed without further review.

### CODE REVIEW

**Comment by sushi2k** [comment]
Thanks @WuglyakBolgoink! 
@emartynov can you please do a QA of this change?

**Review by emartynov — APPROVED** [review]
Magnificient!! 

Спасибо большое за правки 👍

**Comment by emartynov** [comment]
@sushi2k good changes! Shame as a native speaker I slipped such mistakes. As well more natural rephrase.

**Comment by sushi2k** [comment]
Cool. Thanks for the quick feedback @emartynov! 

Thanks for the suggestions @WuglyakBolgoink 👍

**Review by sushi2k — APPROVED** [review]

**Pull request merged**
