### PR TITLE
Update the V4 with session protection details.

### PR DESCRIPTION
**Pull request by commjoen**
Added a few items to session protection (4.8)

### CODE REVIEW

**Comment by b-mueller** [comment]
Can we make this a bit more specific? How would you usually implement this? Binding session IDs to IP addresses?

**Comment by commjoen** [comment]
This is often done by using session identifiers and using payload encryption. By using different keys per session, you cannot take over, unless you have the same keying material.
Binding against ip is not a good idea in general, this would mean that, once you switch from wifi to 4G for instance, you are in trouble..

**Comment by b-mueller** [comment]
Hehe you and your payload encryption :) Isn't this then already implied by:

V5.8: "Verify that the app uses additional payload encryption in case of a broken SSL implementation on the device."

We could shorten in to V5.8: "Verify that the app uses additional payload encryption."

Which would then have the effect of both additional data protection and binding the session to the specific client?

**Comment by commjoen** [comment]
After given it some extra thought I think i rather let this be technique independent: if you don't want to have payload-encryption, then one should be able to use an alternative technique (sequencing, ip's, etc.)

**Comment by b-mueller** [comment]
Added with some re-wording:

4.9	Verify that the app prevents session hijacking by a remote adversary (e.g. by binding the session to the client IP address, or indirectly by using payload encryption).			✓	✓

**Pull request closed without merging**
