### PR TITLE
Added pic for French Translation and CC 4.0 in 0x02

### PR DESCRIPTION
**Pull request by sushi2k**

### CODE REVIEW

**Comment by romualdszkudlarek** [comment]
Ok

**Comment by sushi2k** [comment]
I also removed ""app isolation" from V8. See commit https://github.com/OWASP/owasp-masvs/pull/171/commits/a3f411e788963693b67877a5dab6874ed7f0bca6 This is not a category anymore.

**Comment by sushi2k** [comment]
Could you please approve @romualdszkudlarek

**Comment by romualdszkudlarek** [comment]
Ok

**Pull request merged**
