### PR TITLE
Update 0x09-V4-Authentication_and_Session_Management Requirements.md

### PR DESCRIPTION
**Pull request by sushi2k**
Added biometric authentication toV4.
Should also somehwere add something like this (is of course also applicable to input validation), to ensure that also server side controls are available where client side controls are enforced:
+| 4.6 | Verify that for all client side controls also server side control are implemented. | ✓ | ✓ | ✓ | ✓ 

Added JavaScriptInterace to V6.

### CODE REVIEW

**Comment by sushi2k** [comment]
See also https://github.com/OWASP/owasp-masvs/issues/15, for update of Chapter V7

**Comment by sushi2k** [comment]
True, the wording is pretty bad. We can phrase it as described in the Android Security Tipps:

"In general, we recommend exposing addJavaScriptInterface() only to JavaScript that is contained within your application APK." (see https://developer.android.com/training/articles/security-tips.html#WebView)

So the requirement can be:
* When implementing addJavaScriptInterface ensure that it is only exposed to JavaScript contained within your APK.

**Comment by b-mueller** [comment]
Yeah, makes more sense!

**Comment by sushi2k** [comment]
Just updated the Pull request with the addJavaScriptInterface requirement.

**Comment by b-mueller** [comment]
"Verify that Static Application Security Testing (SAST) is part of the development lifecycle."

I think we should have a more generic requirement for a secure SDLC to exist, in the architecture chapter.

**Comment by b-mueller** [comment]
JavaScript stuff, SAST and DAST were added. I'm leaving out the biometrics stuff for now, this is part of a longer discussion on the auth and crypto requirements.

**Pull request closed without merging**
