### PR TITLE
Customer education

### PR DESCRIPTION
**Pull request by commjoen**
First attempt for creating customer education standard to facilitate the discussion on #36.
I have also included some other controls for which I think that they were still missing.

### CODE REVIEW

**Comment by b-mueller** [comment]
Good additions. Here is a couple of questions:

> "Verify that the user can verify which PII is stored on the device by the app."

What exactly does it mean? That the user is informed about the types of PII stored? How would this look in practice? E.g. a menu item where this is shown? Or just part of a disclaimer?

For most of the points in this chapter, we should come up with a sample disclaimer / user information text in the MSTG.

> "Verify that the app educates the user on how it should be used (e.g.: whether you can manage active devices somewhere, whether it is allowed to use it with multiple devices in parallel)."

> "Verify that the user can manage a set of whitelisted/blacklisted devices (both web & apps) on which sessions have taken place (e.g. view session-origin history, blacklist certain origins from which a session took place)."

Useful feature but quite a lot to ask from both users and developers. Should we move that to at least level 3?

**Comment by commjoen** [comment]
About your first item: maybe it is a better idea to:
" Verify that the user is informed about which PII is stored on the device by the app and by the server". Because letting a user verify what is stored where is actually not so easy.

About your second point: I think you could have them at l3 as well. Note that many apps and online products/services (github, many banks, twitter, google, facebook, etc.) already have this implemented.

**Comment by commjoen** [comment]
Updated based on feedback :) please let me know what I have to change/add :)

**Comment by commjoen** [comment]
Updated based on feedback :) please let me know what I have to change/add :)

**Pull request merged**
