### PR TITLE
Masvs ru fix

### PR DESCRIPTION
**Pull request by RedHotHub**
Russian translation grammar mistakes have been fixed.

### CODE REVIEW

**Comment by commjoen** [comment]
sorry for being a bit late to the party , I hope to review your PR soon ;-)

**Comment by commjoen** [comment]
Grammer check completed (took a while as I am not a native speaker... will double-check content this week)

**Comment by joshriggsdotcom** [comment]
Lol thanks


Sent from my Sprint Samsung Galaxy S8+.
-------- Original message --------From: Jeroen Willemsen <notifications@github.com> Date: 10/11/18  7:41 AM  (GMT-08:00) To: OWASP/owasp-masvs <owasp-masvs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [OWASP/owasp-masvs] Masvs ru fix (#137) 
Grammer check completed (took a while as I am not a native speaker... will double-check content this week)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OWASP/owasp-masvs","title":"OWASP/owasp-masvs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/OWASP/owasp-masvs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@commjoen in #137: Grammer check completed (took a while as I am not a native speaker... will double-check content this week)"}],"action":{"name":"View Pull Request","url":"https://github.com/OWASP/owasp-masvs/pull/137#issuecomment-428976873"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OWASP/owasp-masvs/pull/137#issuecomment-428976873",
"url": "https://github.com/OWASP/owasp-masvs/pull/137#issuecomment-428976873",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [OWASP/owasp-masvs] Masvs ru fix (#137)",
"sections": [
{
"text": "",
"activityTitle": "**Jeroen Willemsen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@commjoen",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"OWASP/owasp-masvs\",\n\"issueId\": 137,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"OWASP/owasp-masvs\",\n\"pullRequestId\": 137\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/OWASP/owasp-masvs/pull/137#issuecomment-428976873"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385012423\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by kysokzla** [comment]
@commjoen @joshriggsdotcom hi guys, i've reviewed the PR and it contains grammar fixes as it was mentioned above as well as more accurate and proper translation of the content. No semantic load changes was performed here compared to original Russian translation.

**Comment by commjoen** [comment]
Thanks @kysokzla and thank you for your fixes @RedHotHub ! You guys rock!

**Comment by commjoen** [comment]
@kysokzla  & @RedHotHub are you on Owasp Slack? because it would be nice to collaborate a bit closer i guess to speed up the russian translations. And it gets easier to nudge me then to speed my response up 👍 .

**Comment by commjoen** [comment]
Hi there! 
@RedHotHub , @kysokzla  & Dmitry Tereshin: can you email me about your names ? So i can put you in  https://github.com/OWASP/owasp-masvs/pull/142 as contributors & revieweiers

**Pull request merged**
