### PR TITLE
Update 0x07-V2-Data_Storage_and_Privacy_requirements.md

### PR DESCRIPTION
**Pull request by TmmmmmR**

### CODE REVIEW

**Comment by b-mueller** [comment]
I made this a level 2 requirement and moved it to 2.10. Also removed the reference to iOS (see issue #5 ).

**Comment by b-mueller** [comment]
I also made it a L1 requirement and moved it to 6.8.

**Comment by b-mueller** [comment]
Hey @TmmmmmR , isn't that actually a duplicate?

2.8: Verify that sensitive data, such as passwords and credit card numbers, is not exposed through the user interface, and does not leak to screenshots.

2.10: Verify that the app removes sensitive data from views when backgrounded.

This refers to the automatic screenshot that's taken when the app is backgrounded right? So can we say that's covered by 2.8 already?

**Comment by TmmmmmR** [comment]
Yes it is. Because iOS takes a screenshot every time an app is sent to the background.

But we need to avoid the confusion between a screenshot maded by a user and a screenshot maded by iOS system after backgrounding an app. 

We can say for example : 

2.8: Verify that sensitive data, such as passwords and credit card numbers, is not exposed through the user interface, and does not leak to screenshots maded by the system after backgrounding an app.

Then we can remove 2.10

What do you think ?

**Pull request merged**
